# El Project Key
sonar.projectKey=sgau-backend

# Las carpetas server
sonar.sources=server

# La carpeta pruebas
sonar.tests=tests

# La ruta de guardado del reporte de cobertura en formato LCOV
sonar.javascript.lcov.reportPaths=coverage/lcov.info