# El Project Key
sonar.projectKey=sgau-backend

# Las carpetas donde está tu código real a evaluar
sonar.sources=server

# La carpeta donde están tus pruebas
sonar.tests=tests

# La ruta donde Jest guarda el reporte de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info